Transformación de encuestas electorales del Centro de Investigaciones Sociológicas (CIS).

Cada encuesta debe contener, cuando disponga de los datos pertinentes, de variable con el recuerdo de voto de esa elección,
de la misma elección en el periodo anterior y de la elección autonómica/general anterior.

Estas variables deben denominarse con las siguientes reglas:

RV - Para indicar Recuerdo de Voto o INTENción de voto.

AUT - Para indicar si se trata de unas elecciones AUTonómicas o GENerales.

XX - Para indicar el año de esas elecciones

AGR - Para señalar todas las variables que han sido agregadas en nuestro trabajo y no proceden directamente del fichero proporcionado 
por el CIS.

Así, la variable de recuerdo de voto autonómico para unas elecciones celebradas en 2011 se denominaría 'RVAUT11AGR'.

Las variables solicitadas son:

**INTAUT**: intención de voto, para encuestas preelectorales.

**RVAUT**: recuerdo de voto en elecciones autonómicas. Idealmente, con el añadido del año podrían distinguirse las elecciones recientes de las de la legislatura anterior.

**RVGEN**: recuerdo de voto en elecciones generales. Idealmente, con el añadido del año podrían distinguirse las elecciones recientes de las de la legislatura anterior.

**ESTUDIOS**: nivel de estudios del entrevistado.

**EDAD**: años que cumplió el entrevistado en su último cumpleaños.

**OCUPACIÓN**: situación laboral de la persona entrevistada.

----
☑ Redactar una to do list.

☑ Combine the variables 'Recuerdo.reciente' & 'Otro.recuerdo' in order to get a new variable capturing all the possible answers regarding interveews voting behaviour.

☑ Same for voting intention.

☑ Add to code a way to capture a 'year reference' for voting behaviour variables.

☐ Add code to generate a table using voting intention variable in pre-election surveys.

☐ Check the tables created by the code and how they look in MS Excel.
    ☐ If possible, consider the pros and cons of using the package "WriteXLS" in this process. 

☐ Check weights in relative frequency tables.

☑ Check the file structure and remove any "\.Rhistory$" file. These code should do the trick:
    ``` {r}
    list.files(path = ".", pattern = "\\.Rhistory$", recursive = T, all.files = T) %>%
    file.remove()
    ```
